# name: ci/cd pipeline

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: self-hosted
#     steps:
#       - name: Check source
#         uses: actions/checkout@v3
      
#       - name: Login to Docker Hub
#         env:
#           username: ${{ secrets.DOCKER_NAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#         run: docker login -u $username -p $password
        
#       - name: Build docker image
#         run: docker build -t cicd-pipeline .
        
#       - name: push image to docker hub
#         run: docker push saurabh0540/cicd-pipeline:latest






name: ci pipeline

on: # specify the build to trigger the automated ci/cd
    push:
        branches:
            - "main"

jobs:
    build:
        name: Build Docker image
        runs-on: ubuntu-latest # specify the build machine
        steps:
            - # checkout to the repository on the build machine
                name: Checkout
                uses: actions/checkout@v3
            - # login to Docker Hub using the secrets provided
                name: Login to Docker Hub
                uses: docker/login-action@v2
                with:
                  username: ${{ secrets.DOCKER_NAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}
            - # create a build kit builder instance
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2
            - # build the container image and push it to Docker \
                # Hub with the name clockbox.
                name: Build and push
                uses: docker/build-push-action@v4
                with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: $/cicd-pipeline:latest
