name: ci/cd pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        env:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $username -p $password
        
      - name: Build docker image
        run: docker build -t cicd-pipeline .
        
      - name: push image to docker hub
        run: docker push saurabh0540/cicd-pipeline:latest
