name: CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check source
        uses: actions/checkout@v3
        
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker image
        run: docker build -t saurabh0540/cicd-pipeline .
        
      - name: push image to docker hub
        run: docker push saurabh0540/cicd-pipeline:latest

