name: ci/cd pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check source
        uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build docker image
        run: docker build -t cicd-pipeline .
        
      - name: push image to docker hub
        run: docker push saurabh0540/cicd-pipeline:latest
