name: cd pipeline

on:
  workflow_run:
    workflows: ["ci pipeline"]
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: pull docker image
        run: sudo docker pull saurabh0540/cicd-pipeline:latest
        
      - name: delete old docker container
        run: sudo docker rm -f cicd-pipeline-container || true
        
      - name: run docker container
        run: sudo docker run -d -p 8080:8080 --name cicd-pipeline-container saurabh0540/cicd-pipeline
