name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t saurabh0540/cicd-pipeline:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_NAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image to Docker Hub
        run: docker push saurabh0540/cicd-pipeline:latest

      - name: SSH into AWS Instance and Run Docker
        uses: appleboy/ssh-action@v0.4.0  # Specify a specific release version
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
          port: ${{ secrets.AWS_SSH_PORT }}
          script: |
            # Pull the Docker image on AWS Ubuntu
            docker pull saurabh0540/cicd-pipeline:latest

            # Run the Docker container
            docker run -d --name cicd-pipeline-container -p 8080:80 saurabh0540/cicd-pipeline:latest
